version: '3.8'

services:
  backend:
    image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/backend:latest
    container_name: build_master_backend_prod
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ACCES_TOKEN_SECRET=${ACCES_TOKEN_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    ports:
      - "3000:3000"

  frontend:
    image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/frontend:latest
    container_name: build_master_frontend_prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

# We do not include 'db' here because we are using Google Cloud SQL 
# which is managed outside of this docker-compose file.
